blank_issues_enabled: true
contact_links:
  - name: 📚 Nuxt 3 Documentation
    url: https://nuxt.com/docs/getting-started/testing
    about: Check the documentation for usage with Nuxt 3
  - name: 📚 Nuxt 2 Documentation
    url: https://v0.test-utils.nuxtjs.org/
    about: Check the documentation for usage with Nuxt 2
  - name: 💬 Discussions
    url: https://github.com/nuxt/test-utils/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
